create table season (
	rank serial primary key,
	day date,
	Team varchar(50),
	Opponent varchar(50),
	WinLoss varchar(50),
	R integer,
	RA integer,
	H integer,
	Doubles integer,
	Triples integer,
	HR integer,
	RBI integer,
	BB integer,
	IBB integer,
	SO integer,
	HBP integer,
	SH integer,
	SF integer,
	ROE integer,
	GDP integer,
	SB integer,
	CS integer,
	aLI numeric,
	LOB integer,
	NumPlayers integer,
	GameLength integer
)
